# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Miniconda
        run: |
          wget -qO- https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | bash -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          $HOME/miniconda/bin/conda init bash
        shell: bash -l {0}

      - name: Setup environment using Conda
        run: |
          source $HOME/.bashrc
          conda env create -f environment.yml
          conda activate myenv  # Replace 'myenv' with the name of your environment
        shell: bash -l {0}

      - name: Run tests
        run: |
          source $HOME/.bashrc
          conda activate myenv  # Replace 'myenv' with the name of your environment
          pytest  # Adjust this command based on your testing framework
        shell: bash -l {0}
