# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Match the Python version in your environment.yml

      - name: Install Miniconda
        run: |
          wget -qO- https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | bash -b -p ~/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          ~/miniconda/bin/conda init bash

      - name: Setup environment using Conda
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml
          conda activate myenv  # Replace 'myenv' with the name of your environment

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate myenv  # Replace 'myenv' with the name of your environment
          pytest  # Adjust this command based on your testing framework
